version: '3.8'

services:

  redis:

    image: redis:7.0.11-alpine
    hostname: redis
    ports:
      - 6379:6379

  django:

    container_name: django
    hostname: django
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost, 127.0.0.1
    depends_on:
      - redis

  celery:
      build:
          context: .
          dockerfile: Dockerfile.django
      command: celery --app=dcelery worker -l info
      links:
          - redis
      depends_on:
          - redis
          - django